name: Node.js CI

on:
  push:
    branches: [ block* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: branch name  
      run: echo running on branch ${GITHUB_REF##*/}
    - name: run ci
      run: cd $(echo "${GITHUB_REF##*/}") && npm ci
    - name: build
      run: cd $(echo "${GITHUB_REF##*/}") && npm run build --if-present
    - name: run test
      run: cd $(echo "${GITHUB_REF##*/}") && npm test

